# Generated by Django 5.0.6 on 2024-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeonapp', '0003_workshopformdetails_delete_workshopformdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
