# Generated by Django 5.0.6 on 2024-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aeonapp', '0005_remove_publicationpaper_abstract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=25)),
                ('institute', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=25)),
                ('queries', models.CharField(max_length=100)),
            ],
        ),
    ]
